export { MainPage } from './Mainpage/MainPage';
export { Modal, Mdl } from './Modal/Modal';
// export ProductDetails from './ProductDetails/ProductDetails';
// export ProductCard from './ProductCard/ProductCard';
export { NotFound } from './Notfound/NotFound';
export { Title } from './Title/Title';
export { Favourites } from './Favourites/Favourites';
export { Notifier } from './Notifier/Notifier';
export { Unsubscribe } from './Unsubscribe/Unsubscribe';
export { Checkout } from './Checkout';
export { ClientProfile } from './ClientProfile/ClientProfile';
export { TermsConditions } from './TermsConditions/TermsConditions';
export { PrivacyPolicy } from './PrivacyPolicy/PrivacyPolicy';
export { Order } from './Order/Order';
