export {MainPage} from './Mainpage/MainPage'
export {Products} from './Products/Products'
export {ProductDetails} from './Products/ProductDetails'
export {ProductCard} from './ProductCard/ProductCard'
export {Modal, Mdl} from './Modal/Modal'
export {NotFound} from './Notfound/NotFound'
export {Title} from './Title/Title'
export {Favourites} from './Favourites/Favourites'